site_name: 雨下不停的知识库
site_url: 'http://library.dcgamer.top'
site_author: lamber

# 设置Git相关信息
repo_name: 'lamber'
repo_url: 'https://github.com/LamberMa/The-knowledge-Base.git'
theme:
  name: material
  highlightjs: true
  hljs_style: 'Xt 256'
  hljs_languages:
    - yaml
    - rust
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  language: 'zh'
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

extra:
  social:
    - type: github
      link: https://github.com/caimengzhi
  search:
    language: 'jp'

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - 容器云技术:
    - Docker:
      - Docker基础: 
        - '01-Docker介绍': 'docker/01-Docker基础使用/01-Docker介绍.md'
        - '02-Docker网络和存储': 'docker/01-Docker基础使用/02-Docker数据存储和网络访问.md'
        - '03-镜像的构建': 'docker/01-Docker基础使用/03-手动构建镜像.md'
        - '04-Dockerfle': 'docker/01-Docker基础使用/04-DockerFile.md'
    - Kubernetes编排:
      - '01-k8s纯手工部署': 'kubernetes/01-k8s纯手工部署.md'
  - Django学习笔记:
    - 'Django DRF':
      - '01-Restful介绍': django/DRF/01-Restful.md
      - '02-Request封装': django/DRF/02-Request的封装.md
      - '03-DRF的认证': django/DRF/03-DRF的认证.md
      - '04-DRF的权限': django/DRF/04-DRF权限.md 
      - '05-DRF访问限制': django/DRF/05-DRF访问限制.md
      - '06-DRF版本&解析器': django/DRF/06-DRF版本&解析器.md
      - '07-DRF序列化': django/DRF/07-DRF序列化.md